/** @format */

import { ReduxProvider } from "lib/ReduxProvider";
import type { Metadata } from "next";
import "./globals.css";
import { GeistSans } from "geist/font/sans";
import { Toaster } from "./components/shadcn/ui/toaster";
import React from "react";
import { AuthLoadingProvider } from "@/context/AuthLoadingProvider";
import { AuthProvider } from "@/context/AuthProvider";

// const montserrat = Montserrat({
//     subsets: ["latin"],
//     display: "swap",
// });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
                                       children
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body className={GeistSans.className + " flex flex-col h-screen"}>
        <ReduxProvider>
            <AuthLoadingProvider>
                <AuthProvider>
                    {/* nextjs, redux-toolkit, tailwind, shadcn/ui, appwrite */}
                    {children}
                </AuthProvider>
            </AuthLoadingProvider>
        </ReduxProvider>
        <Toaster />
        </body>
        </html>
    );
}
